#!/bin/bash 
scancel -n berDFE00
scancel -n berDFE01
scancel -n berDFE02
scancel -n berDFE03
scancel -n berDFE04
scancel -n berDFE05
scancel -n berDFE06
scancel -n berDFE07
scancel -n berDFE08
scancel -n berDFE09
scancel -n berDFE10
scancel -n berDFE11
scancel -n berDFE12
scancel -n berDFE13
scancel -n berDFE14
scancel -n berDFE15
scancel -n berDFE16
scancel -n berDFE17
scancel -n berDFE18
scancel -n berDFE19
scancel -n berDFE20
scancel -n berDFE21
scancel -n berDFE22
scancel -n berDFE23
scancel -n berDFE24
scancel -n berDFE25
scancel -n berDFE26
scancel -n berDFE27
scancel -n berDFE28
scancel -n berDFE29
scancel -n berDFE30
scancel -n berDFE31
scancel -n berDFE32
scancel -n berDFE33
scancel -n berDFE34
scancel -n berDFE35
scancel -n berDFE36
scancel -n berDFE37
scancel -n berDFE38
scancel -n berDFE39
scancel -n berDFE40
scancel -n berDFE41
scancel -n berDFE42
scancel -n berDFE43
scancel -n berDFE44
scancel -n berDFE45
scancel -n berDFE46
scancel -n berDFE47
scancel -n berDFE48
scancel -n berDFE49
scancel -n berDFE50
scancel -n berDFE51
scancel -n berDFE52
scancel -n berDFE53
scancel -n berDFE54
scancel -n berDFE55
scancel -n berDFE56
scancel -n berDFE57
scancel -n berDFE58
scancel -n berDFE59
scancel -n berDFE60
scancel -n berDFE61
scancel -n berDFE62
scancel -n berDFE63
scancel -n berDFE64
